inventariadoPractica/routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductoController;
use App\Http\Controllers\CategoriaController;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\VentaController;
use App\Http\Controllers\InventarioController;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// Grupo de rutas protegidas por autenticación
Route::middleware('auth')->group(function () {
    // Rutas de perfil
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // Rutas de productos
    Route::resource('productos', ProductoController::class);

    // Rutas de categorías
    Route::resource('categorias', CategoriaController::class);

    // Rutas de clientes
    Route::resource('clientes', ClienteController::class);

    // Rutas de ventas
    Route::resource('ventas', VentaController::class);

    // Rutas de inventarios
    Route::resource('inventarios', InventarioController::class);
});

require __DIR__.'/auth.php';

inventariadoPractica/app/Models/Inventario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Inventario extends Model
{
    use HasFactory;

    protected $primaryKey = 'id_inventario';

    protected $fillable = [
        'id_producto',
        'id_categoria',
        'fecha_entrada',
        'fecha_salida',
        'motivo',
        'movimiento',
        'cantidad',
    ];

    public function producto()
    {
        //Un registro de inventario pertenece a un producto
        return $this->belongsTo(Producto::class, 'id_producto');
    }

    public function categoria()
    {   
        //Un registro de inventario pertenece a una categoria
        return $this->belongsTo(Categoria::class, 'id_categoria');
    }
}

inventariadoPractica/app/Http/Controllers/InventarioController.php
<?php

namespace App\Http\Controllers;

use App\Models\Inventario;
use App\Models\Producto;
use App\Models\Categoria;
use Illuminate\Http\Request;

class InventarioController extends Controller
{
    public function index(Request $request)
    {
        $query = Inventario::with(['producto', 'categoria']);

        if ($request->has('search')) {
            $search = $request->input('search');
            $query->whereHas('producto', function ($q) use ($search) {
                $q->where('nombre', 'like', '%' . $search . '%');
            });
        }

        $inventarios = $query->get();

        return view('inventarios.inventarios', compact('inventarios'));
    }

    public function create()
    {
        $productos = Producto::all();
        $categorias = Categoria::all();
        return view('inventarios.create', compact('productos', 'categorias'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'id_producto' => 'required|exists:productos,id_producto',
            'id_categoria' => 'required|exists:categorias,id_categoria',
            'fecha_entrada' => 'required|date',
            'fecha_salida' => 'nullable|date',
            'motivo' => 'required|string|max:255',
            'movimiento' => 'required|string|max:255',
            'cantidad' => 'required|integer',
        ]);

        Inventario::create($request->all());
        return redirect()->route('inventarios.index')->with('success', 'Inventario añadido exitosamente');
    }

    public function edit(Inventario $inventario)
    {
        $productos = Producto::all();
        $categorias = Categoria::all();
        return view('inventarios.edit', compact('inventario', 'productos', 'categorias'));
    }

    public function update(Request $request, Inventario $inventario)
    {
        $request->validate([
            'id_producto' => 'required|exists:productos,id_producto',
            'id_categoria' => 'required|exists:categorias,id_categoria',
            'fecha_entrada' => 'required|date',
            'fecha_salida' => 'nullable|date',
            'motivo' => 'required|string|max:255',
            'movimiento' => 'required|string|max:255',
            'cantidad' => 'required|integer',
        ]);

        $inventario->update($request->all());
        return redirect()->route('inventarios.index')->with('success', 'Inventario actualizado exitosamente');
    }

    public function destroy(Inventario $inventario)
    {
        $inventario->delete();
        return redirect()->route('inventarios.index')->with('success', 'Inventario eliminado exitosamente');
    }
}

inventariadoPractica/resources/views/inventarios/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container mx-auto px-4">
    <h1 class="text-2xl font-bold mb-4">Añadir Inventario</h1>

    <form id="inventario-form" action="{{ route('inventarios.store') }}" method="POST">
        @csrf

        <div class="mb-4">
            <label for="id_producto" class="block text-gray-700">Producto</label>
            <select name="id_producto" id="id_producto" class="w-full border-2 border-gray-300 p-2 rounded" required>
                <option value="" disabled selected>Seleccione un producto</option>
                @foreach($productos as $producto)
                    <option value="{{ $producto->id_producto }}" {{ old('id_producto') == $producto->id_producto ? 'selected' : '' }}>{{ $producto->nombre }}</option>
                @endforeach
            </select>
            @error('id_producto')
                <div class="text-red-500 mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-4">
            <label for="id_categoria" class="block text-gray-700">Categoría</label>
            <select name="id_categoria" id="id_categoria" class="w-full border-2 border-gray-300 p-2 rounded" required>
                <option value="" disabled selected>Seleccione una categoría</option>
                @foreach($categorias as $categoria)
                    <option value="{{ $categoria->id_categoria }}" {{ old('id_categoria') == $categoria->id_categoria ? 'selected' : '' }}>{{ $categoria->nombre_categoria }}</option>
                @endforeach
            </select>
            @error('id_categoria')
                <div class="text-red-500 mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-4">
            <label for="fecha_entrada" class="block text-gray-700">Fecha de Entrada</label>
            <input type="date" name="fecha_entrada" id="fecha_entrada" class="w-full border-2 border-gray-300 p-2 rounded" value="{{ old('fecha_entrada') }}" required>
            @error('fecha_entrada')
                <div class="text-red-500 mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-4">
            <label for="fecha_salida" class="block text-gray-700">Fecha de Salida</label>
            <input type="date" name="fecha_salida" id="fecha_salida" class="w-full border-2 border-gray-300 p-2 rounded" value="{{ old('fecha_salida') }}">
            @error('fecha_salida')
                <div class="text-red-500 mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-4">
            <label for="motivo" class="block text-gray-700">Motivo</label>
            <input type="text" name="motivo" id="motivo" class="w-full border-2 border-gray-300 p-2 rounded" value="{{ old('motivo') }}" required>
            @error('motivo')
                <div class="text-red-500 mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-4">
            <label for="movimiento" class="block text-gray-700">Movimiento</label>
            <select name="movimiento" id="movimiento" class="w-full border-2 border-gray-300 p-2 rounded" required>
                <option value="Entrada" {{ old('movimiento') == 'Entrada' ? 'selected' : '' }}>Entrada</option>
                <option value="Salida" {{ old('movimiento') == 'Salida' ? 'selected' : '' }}>Salida</option>
            </select>
            @error('movimiento')
                <div class="text-red-500 mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-4">
            <label for="cantidad" class="block text-gray-700">Cantidad</label>
            <input type="number" name="cantidad" id="cantidad" class="w-full border-2 border-gray-300 p-2 rounded" value="{{ old('cantidad') }}" required>
            @error('cantidad')
                <div class="text-red-500 mt-2">{{ $message }}</div>
            @enderror
        </div>

        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Añadir</button>
    </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    document.getElementById('inventario-form').addEventListener('submit', function(event) {
        const fechaEntrada = document.getElementById('fecha_entrada').value;
        const fechaSalida = document.getElementById('fecha_salida').value;

        if (fechaSalida && fechaEntrada > fechaSalida) {
            event.preventDefault();
            Swal.fire({
                icon: 'error',
                title: 'Error',
                text: 'La fecha de salida no puede ser antes que la fecha de entrada.',
                showConfirmButton: true
            });
        }
    });

    @if(session('success'))
        Swal.fire({
            icon: 'success',
            title: 'Éxito',
            text: '{{ session('success') }}',
            showConfirmButton: false,
            timer: 3000
        });
    @endif
</script>
@endsection

inventariadoPractica/resources/views/inventarios/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container mx-auto px-4">
    <h1 class="text-2xl font-bold mb-4">Editar Inventario</h1>

    <form action="{{ route('inventarios.update', $inventario->id_inventario) }}" method="POST">
        @csrf
        @method('PUT')


        <div class="mb-4">
            <label for="id_producto" class="block text-gray-700">Producto</label>
            <select name="id_producto" id="id_producto" class="w-full border-2 border-gray-300 p-2 rounded" required>

                @foreach($productos as $producto)
                    <option value="{{ $producto->id_producto }}" {{ old('id_producto') == $producto->id_producto ? 'selected' : '' }}>{{ $producto->nombre }}</option>
                @endforeach
            </select>
            @error('id_producto')
                <div class="text-red-500 mt-2">{{ $message }}</div>
            @enderror
        </div>
        <div class="mb-4">
            <label for="id_categoria" class="block text-gray-700">Categoría</label>
            <select name="id_categoria" id="id_categoria" class="w-full border-2 border-gray-300 p-2 rounded" required>
                <option value="" disabled>Seleccione una categoría</option>
                @foreach($categorias as $categoria)
                    <option value="{{ $categoria->id_categoria }}" {{ $inventario->id_categoria == $categoria->id_categoria ? 'selected' : '' }}>{{ $categoria->nombre_categoria }}</option>
                @endforeach
            </select>
            @error('id_categoria')
                <div class="text-red-500 mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-4">
            <label for="fecha_entrada" class="block text-gray-700">Fecha de Entrada</label>
            <input type="date" name="fecha_entrada" id="fecha_entrada" class="w-full border-2 border-gray-300 p-2 rounded" value="{{ $inventario->fecha_entrada }}" required>
            @error('fecha_entrada')
                <div class="text-red-500 mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-4">
            <label for="fecha_salida" class="block text-gray-700">Fecha de Salida</label>
            <input type="date" name="fecha_salida" id="fecha_salida" class="w-full border-2 border-gray-300 p-2 rounded" value="{{ $inventario->fecha_salida }}">
            @error('fecha_salida')
                <div class="text-red-500 mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-4">
            <label for="motivo" class="block text-gray-700">Motivo</label>
            <input type="text" name="motivo" id="motivo" class="w-full border-2 border-gray-300 p-2 rounded" value="{{ $inventario->motivo }}" required>
            @error('motivo')
                <div class="text-red-500 mt-2">{{ $message }}</div>
            @enderror
        </div>



        <div class="mb-4">
            <label for="movimiento" class="block text-gray-700">Movimiento</label>
            <select name="movimiento" id="movimiento" class="w-full border-2 border-gray-300 p-2 rounded" required>
                <option value="Entrada" {{ $inventario->movimiento == 'Entrada' ? 'selected' : '' }}>Entrada</option>
                <option value="Salida" {{ $inventario->movimiento == 'Salida' ? 'selected' : '' }}>Salida</option>
            </select>
            @error('movimiento')
                <div class="text-red-500 mt-2">{{ $message }}</div>
            @enderror
        </div>


        <div class="mb-4">
            <label for="cantidad" class="block text-gray-700">Cantidad</label>
            <input type="text" name="cantidad" id="cantidad" class="w-full border-2 border-gray-300 p-2 rounded" value="{{ $inventario->cantidad }}" required>
            @error('cantidad')
                <div class="text-red-500 mt-2">{{ $message }}</div>
            @enderror
        </div>

        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Actualizar</button>
    </form>
</div>
@endsection

inventariadoPractica/resources/views/inventarios/inventarios.blade.php
@extends('layouts.app')

@section('content')
<div class="container mx-auto px-4">
    <h1 class="text-2xl font-bold mb-4">Inventario</h1>
    <a href="{{ route('inventarios.create') }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-4 inline-block">Añadir Inventario</a>

    <!-- Formulario de búsqueda -->
    <form action="{{ route('inventarios.index') }}" method="GET" class="mb-4">
        <input type="text" name="search" id="search" value="{{ request('search') }}" placeholder="Buscar producto..." class="border border-gray-300 rounded py-2 px-4">
        <button type="submit" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Buscar</button>
        <button type="button" id="clear-search" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Limpiar</button>
    </form>

    <table class="min-w-full bg-white">
        <thead>
            <tr>
                <th class="py-2">Producto</th>
                <th class="py-2">Categoría</th>
                <th class="py-2">Fecha Entrada</th>
                <th class="py-2">Fecha Salida</th>
                <th class="py-2">Motivo</th>
                <th class="py-2">Movimiento</th>
                <th class="py-2">Cantidad</th>
                <th class="py-2">Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach($inventarios as $inventario)
                <tr>
                    <td class="py-2">{{ $inventario->producto->nombre }}</td>
                    <td class="py-2">{{ $inventario->categoria->nombre_categoria }}</td>
                    <td class="py-2">{{ $inventario->fecha_entrada }}</td>
                    <td class="py-2">{{ $inventario->fecha_salida }}</td>
                    <td class="py-2">{{ $inventario->motivo }}</td>
                    <td class="py-2">{{ $inventario->movimiento }}</td>
                    <td class="py-2">{{ $inventario->cantidad }}</td>
                    <td class="py-2">
                        <a href="{{ route('inventarios.edit', $inventario->id_inventario) }}" class="bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded">Editar</a>
                        <form action="{{ route('inventarios.destroy', $inventario->id_inventario) }}" method="POST" class="inline-block">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Eliminar</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>

<script>
document.getElementById('clear-search').addEventListener('click', function() {
    document.getElementById('search').value = '';
    window.location.href = "{{ route('inventarios.index') }}";
});
</script>
@endsection