practica1Laravel/routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProductoController;
use App\Http\Controllers\CategoriaController;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\VentaController;
use App\Http\Controllers\InventarioController;


//Login
Route::get('/', function () {
    return view('welcome');
});

//Register
Route::get('/register', function () {
    return view('auth.register');
});

//Dashboard
Route::get('/index', [ProductController::class, 'index'])
    ->middleware(['auth', 'verified'])->name('index');

//Index - Lista de productos
Route::get('/index', [ProductController::class, 'index'])
    ->middleware(['auth', 'verified'])->name('index');

    Route::get('/', function () {
        return view('layouts.app');
    });
    
    Route::get('/productos', function () {
        return view('productos.productos');
    });
    
    Route::get('/categorias', function () {
        return view('categorias.categorias');
    });
    
    Route::get('/ventas', function () {
        return view('ventas.ventas');
    });
    
    Route::get('/inventarios', function () {
        return view('inventarios.inventarios');
    });
    
    Route::get('/clientes', function () {
        return view('clientes.clientes');
    });
    
    // Rutas de productos
    Route::resource('productos', ProductoController::class);
    
    // Rutas de categorías
    Route::resource('categorias', CategoriaController::class);
    
    // Rutas de clientes
    Route::resource('clientes', ClienteController::class);
    
    // Rutas de ventas
    Route::resource('ventas', VentaController::class);
    
    // Rutas de inventarios
    Route::resource('inventarios', InventarioController::class);

require __DIR__.'/auth.php';

practica1Laravel/app/Models/Producto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    use HasFactory;
        

    // Establece 'id_producto' como la clave primaria para el modelo Producto
    protected $primaryKey = 'id_producto';
    protected $fillable = [
        'nombre',
        'categoria_id',
        'pv',
        'pc',
        'fecha_compra',
        'colores',
        'desc_Corta',
        'desc_Larga',
    ];
    

    //Función que define una relación de pertenencia a una categoría
    public function categoria()
    {
        // Un producto pertenece a una categoría
        return $this->belongsTo(Categoria::class, 'categoria_id');
    }


    //Función que define una relación de uno a muchos con el modelo Venta
    public function ventas()
    {
        // Un producto puede tener muchas ventas
        return $this->hasMany(Venta::class, 'id_producto');
    }
}

practica1Laravel/app/Http/Controllers/ProductoController.php
<?php
namespace App\Http\Controllers;

use App\Models\Producto;
use App\Models\Categoria;
use Illuminate\Http\Request;
use App\Models\Cliente;
class ProductoController extends Controller
{
    public function index()
    {
        $productos = Producto::with('categoria')->get();
        return view('productos.productos', compact('productos'));
    }

    public function create()
    {
        $productos = Producto::all(); // Aquí obtenemos todos los productos
        $categorias = Categoria::all();
        $clientes = Cliente::all();
        return view('productos.create', compact('productos', 'categorias', 'clientes')); // Pasamos $productos a la vista
    }
    public function store(Request $request)
    {
        $request->validate([
            'nombre' => 'required|max:255',
            'categoria_id' => 'required|exists:categorias,id_categoria',
            'pv' => 'required|numeric',
            'pc' => 'required|numeric',
            'fecha_compra' => 'required|date',
            'colores' => 'required|max:255',
            'desc_Corta' => 'required|max:255',
            'desc_Larga' => 'required'
        ]);

        Producto::create($request->all());
        return redirect()->route('productos.index')->with('success', 'Producto añadido exitosamente');
    }

    public function edit(Producto $producto)
    {
        $categorias = Categoria::all();
        return view('productos.edit', compact('producto', 'categorias'));
    }

    public function update(Request $request, Producto $producto)
    {
        $request->validate([
            'nombre' => 'required|max:255',
            'categoria_id' => 'required|exists:categorias,id_categoria',
            'pv' => 'required|numeric',
            'pc' => 'required|numeric',
            'fecha_compra' => 'required|date',
            'colores' => 'required|max:255',
            'desc_Corta' => 'required|max:255',
            'desc_Larga' => 'required'
        ]);

        $producto->update($request->all());
        return redirect()->route('productos.index')->with('success', 'Producto actualizado exitosamente');
    }

    public function destroy(Producto $producto)
    {
        $producto->delete();
        return redirect()->route('productos.index')->with('success', 'Producto eliminado exitosamente');
    }
}

practica1Laravel/resources/views/productos/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container mx-auto px-4">
    <div class="max-w-lg mx-auto bg-white p-8 rounded-lg shadow">
        <h1 class="text-2xl font-bold mb-4">Añadir Producto</h1>
        <form action="{{ route('productos.store') }}" method="POST">
            @csrf
            <div class="mb-4">
                <label for="nombre" class="block text-sm font-medium text-gray-700">Nombre</label>
                <input type="text" name="nombre" id="nombre" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50" required>
            </div>
            <div class="mb-4">
                <label for="categoria_id" class="block text-sm font-medium text-gray-700">Categoría</label>
                <select name="categoria_id" id="categoria_id" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50" required>
                    <option value="">Seleccione una categoría</option>
                    @foreach($categorias as $categoria)
                        <option value="{{ $categoria->id_categoria }}">{{ $categoria->nombre_categoria }}</option>
                    @endforeach
                </select>
            </div>
            <div class="mb-4">
                <label for="pv" class="block text-sm font-medium text-gray-700">Productos Vendidos</label>
                <input type="number" name="pv" id="pv" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50" required>
            </div>
            <div class="mb-4">
                <label for="pc" class="block text-sm font-medium text-gray-700">Productos Comprados</label>
                <input type="number" name="pc" id="pc" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50" required>
            </div>
            <div class="mb-4">
                <label for="fecha_compra" class="block text-sm font-medium text-gray-700">Fecha de Compra</label>
                <input type="date" name="fecha_compra" id="fecha_compra" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50" required>
            </div>
            <div class="mb-4">
                <label for="colores" class="block text-sm font-medium text-gray-700">Colores</label>
                <input type="text" name="colores" id="colores" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50" required>
            </div>
            <div class="mb-4">
                <label for="desc_Corta" class="block text-sm font-medium text-gray-700">Descripción Corta</label>
                <textarea name="desc_Corta" id="desc_Corta" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50" required></textarea>
            </div>
            <div class="mb-4">
                <label for="desc_Larga" class="block text-sm font-medium text-gray-700">Descripción Larga</label>
                <textarea name="desc_Larga" id="desc_Larga" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50" required></textarea>
            </div>
            <div class="flex justify-end">
                <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Guardar</button>
            </div>
        </form>
    </div>
</div>
@endsection

practica1Laravel/resources/views/productos/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container mx-auto px-4">
    <div class="max-w-lg mx-auto bg-white p-8 rounded-lg shadow">
        <h1 class="text-2xl font-bold mb-4">Editar Producto</h1>
        <form action="{{ route('productos.update', $producto->id_producto) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="mb-4">
                <label for="nombre" class="block text-sm font-medium text-gray-700">Nombre</label>
                <input type="text" name="nombre" id="nombre" value="{{ $producto->nombre }}" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50" required>
            </div>
            <div class="mb-4">
                <label for="categoria_id" class="block text-sm font-medium text-gray-700">Categoría</label>
                <select name="categoria_id" id="categoria_id" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50" required>
                    @foreach($categorias as $categoria)
                        <option value="{{ $categoria->id_categoria }}" {{ $producto->categoria_id == $categoria->id_categoria ? 'selected' : '' }}>{{ $categoria->nombre_categoria }}</option>
                    @endforeach
                </select>
            </div>
            <div class="mb-4">
                <label for="pv" class="block text-sm font-medium text-gray-700">Productos Vendidos</label>
                <input type="number" name="pv" id="pv" value="{{ $producto->pv }}" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50" required>
            </div>
            <div class="mb-4">
                <label for="pc" class="block text-sm font-medium text-gray-700">Productos Comprados</label>
                <input type="number" name="pc" id="pc" value="{{ $producto->pc }}" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50" required>
            </div>
            <div class="mb-4">
                <label for="fecha_compra" class="block text-sm font-medium text-gray-700">Fecha de Compra</label>
                <input type="date" name="fecha_compra" id="fecha_compra" value="{{ $producto->fecha_compra }}" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50" required>
            </div>
            <div class="mb-4">
                <label for="colores" class="block text-sm font-medium text-gray-700">Colores</label>
                <input type="text" name="colores" id="colores" value="{{ $producto->colores }}" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50" required>
            </div>
            <div class="mb-4">
                <label for="desc_Corta" class="block text-sm font-medium text-gray-700">Descripción Corta</label>
                <textarea name="desc_Corta" id="desc_Corta" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50" required>{{ $producto->desc_Corta }}</textarea>
            </div>
            <div class="mb-4">
                <label for="desc_Larga" class="block text-sm font-medium text-gray-700">Descripción Larga</label>
                <textarea name="desc_Larga" id="desc_Larga" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50" required>{{ $producto->desc_Larga }}</textarea>
            </div>
            <div class="flex justify-end">
                <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Guardar</button>
            </div>
        </form>
    </div>
</div>
@endsection

practica1Laravel/resources/views/productos/productos.blade.php
@extends('layouts.app')

@section('content')
<div class="container mx-auto px-4">
    <div class="flex justify-between items-center mb-4">
        <h1 class="text-2xl font-bold">Lista de Productos</h1>
        <a href="{{ route('productos.create') }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Añadir Producto</a>
    </div>
    <div class="bg-white shadow-md rounded my-6">
        <table class="min-w-full table-auto">
            <thead class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                <tr>
                    <th class="py-3 px-6 text-left">Nombre</th>
                    <th class="py-3 px-6 text-left">Categoría</th>
                    <th class="py-3 px-6 text-left">Prod Vendidos</th>
                    <th class="py-3 px-6 text-left">Prod Comprados</th>
                    <th class="py-3 px-6 text-left">Fecha de Compra</th>
                    <th class="py-3 px-6 text-left">Color</th>
                    <th class="py-3 px-6 text-left">Descripción Corta</th>
                    <th class="py-3 px-6 text-left">Descripción Larga</th>
                    <th class="py-3 px-6 text-left">Acciones</th>
                </tr>
            </thead>
            <tbody class="text-gray-600 text-sm font-light">
                @foreach($productos as $producto)
                    <tr class="border-b border-gray-200 hover:bg-gray-100">
                        <td class="py-3 px-6 text-left whitespace-nowrap">{{ $producto->nombre }}</td>
                        <td class="py-3 px-6 text-left">{{ $producto->categoria->nombre_categoria }}</td>
                        <td class="py-3 px-6 text-left">{{ $producto->pv }}</td>
                        <td class="py-3 px-6 text-left">{{ $producto->pc }}</td>
                        <td class="py-3 px-6 text-left">{{ $producto->fecha_compra }}</td>
                        <td class="py-3 px-6 text-left">{{ $producto->colores }}</td>
                        <td class="py-3 px-6 text-left">{{ $producto->desc_Corta }}</td>
                        <td class="py-3 px-6 text-left">{{ $producto->desc_Larga }}</td>
                        <td class="py-3 px-6 text-left">
                            <div class="flex item-center justify-center">
                                <a href="{{ route('productos.edit', $producto->id_producto) }}" class="bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-1 px-2 rounded">Editar</a>
                                <form action="{{ route('productos.destroy', $producto->id_producto) }}" method="POST" class="ml-1">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded">Eliminar</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection