inventariadoDos/routes/web.php
<?php
use App\Http\Controllers\PDFController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CategoriaController;
use App\Http\Controllers\ProductoController;
use App\Http\Controllers\ProveedorController;
use App\Http\Controllers\InventarioController;
use App\Http\Controllers\CompraController;
use App\Http\Controllers\CotizacionController;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\FormaDePagoController;
use App\Http\Controllers\VendedorController;
use App\Http\Controllers\VentaController;

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::get('/productos',function(){
    return view('productos');
})->middleware(['auth','verified'])->name('productos');


//Rutas para las categorias
Route::resource('categorias', CategoriaController::class);
Route::get('categorias/buscar/{nombre}', [CategoriaController::class, 'buscar'])->name('categorias.buscar');


//Ruta para los productos
Route::resource('productos', ProductoController::class);



//Ruta para los proveedores
Route::resource('proveedores', ProveedorController::class);


//Ruta para Inventarios
Route::resource('inventarios', InventarioController::class);


//Ruta para compras
Route::resource('compras',CompraController::class);

//Ruta para cotizaciones
Route::resource('cotizaciones',CotizacionController::class);

//Ruta para clientes
Route::resource('clientes', ClienteController::class);

//Ruta para formas de pago
Route::resource('formas_de_pago', FormaDePagoController::class);

//Ruta para vendedores
Route::resource('vendedores', VendedorController::class);

Route::get('/api/productos', [ProductoController::class, 'search'])->name('productos.search');


//Ruta para compras
Route::resource('compras', CompraController::class);


//Ruta para ventas
Route::resource('ventas', VentaController::class);

//PDFS
Route::get('ventas/pdf/{id}', [PDFController::class, 'exportarPDFVenta'])->name('ventas.pdf');
Route::get('cotizaciones/pdf/{id}', [PDFController::class, 'exportarPDFCotizacion'])->name('cotizaciones.pdf');
Route::get('compras/pdf/{param}', [PDFController::class, 'exportarPDFCompras'])->name('compras.pdf');
Route::get('inventarios/pdf/{param}', [PDFController::class, 'exportarPDFInventarios'])->name('inventarios.pdf');
Route::get('producto-pdf', [PDFController::class, 'exportarPDFProductos'])->name('productos.pdf');
Route::get('stock_producto-pdf', [PDFController::class, 'exportarPDFstockPorProducto'])->name('stock_por_producto.pdf');
Route::get('proveedores-pdf', [PDFController::class, 'exportarPDFProveedores'])->name('proveedores.pdf');
Route::get('clientes-pdf', [PDFController::class, 'exportarPDFClientes'])->name('clientes.pdf');
Route::get('vendedores-pdf', [PDFController::class, 'exportarPDFVendedores'])->name('vendedores.pdf');
Route::get('formas-pago-pdf', [PDFController::class, 'exportarPDFFormasPago'])->name('formas_pago.pdf');



Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

inventariadoDos/resources/views/vendedores/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container mx-auto px-4">
    <div class="flex justify-center mt-8">
        <div class="w-full max-w-2xl">
            <div class="bg-white shadow-lg rounded-lg overflow-hidden">
                <div class="bg-gray-800 text-white px-6 py-4">
                    <h2 class="text-2xl font-semibold">{{ __('Crear Nuevo Vendedor') }}</h2>
                </div>

                <div class="p-6">
                    <form action="{{ route('vendedores.store') }}" method="POST">
                        @csrf
                        <div class="mb-6">
                            <label for="nombre" class="block text-gray-700 text-sm font-semibold mb-2">Nombre:</label>
                            <input type="text" id="nombre" name="nombre" class="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-500 transition duration-200" required>
                        </div>
                        <div class="mb-6">
                            <label for="correo" class="block text-gray-700 text-sm font-semibold mb-2">Correo:</label>
                            <input type="email" id="correo" name="correo" class="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-500 transition duration-200" required>
                        </div>
                        <div class="mb-6">
                            <label for="telefono" class="block text-gray-700 text-sm font-semibold mb-2">Teléfono:</label>
                            <input type="text" id="telefono" name="telefono" class="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-500 transition duration-200" required>
                        </div>
                        <div class="mb-6">
                            <label for="direccion" class="block text-gray-700 text-sm font-semibold mb-2">Dirección:</label>
                            <input type="text" id="direccion" name="direccion" class="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-500 transition duration-200" required>
                        </div>
                        
                        <div class="flex justify-end space-x-4">
                            <a href="{{ route('vendedores.index') }}" class="bg-gray-500 text-white px-6 py-2 rounded-lg hover:bg-gray-600 focus:outline-none focus:ring focus:ring-gray-300 transition duration-200">Cancelar</a>
                            <button type="submit" class="bg-black text-white px-6 py-2 rounded-lg hover:bg-gray-800 focus:outline-none focus:ring focus:ring-gray-300 transition duration-200">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

inventariadoDos/resources/views/vendedores/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container mx-auto px-4 py-8">
    <div class="bg-white shadow-lg rounded-lg overflow-hidden">
        <div class="px-6 py-4">
            <h1 class="text-2xl font-semibold mb-4">Editar Vendedor</h1>
            <form action="{{ route('vendedores.update', $vendedor->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="mb-4">
                    <label for="nombre" class="block text-sm font-medium text-gray-700">Nombre</label>
                    <input type="text" name="nombre" id="nombre" value="{{ old('nombre', $vendedor->nombre) }}" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
                    @error('nombre')
                        <p class="text-red-500 text-sm mt-1">{{ $message }}</p>
                    @enderror
                </div>
                <div class="mb-4">
                    <label for="correo" class="block text-sm font-medium text-gray-700">Correo</label>
                    <input type="email" name="correo" id="correo" value="{{ old('correo', $vendedor->correo) }}" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
                    @error('correo')
                        <p class="text-red-500 text-sm mt-1">{{ $message }}</p>
                    @enderror
                </div>
                <div class="mb-4">
                    <label for="telefono" class="block text-sm font-medium text-gray-700">Teléfono</label>
                    <input type="text" name="telefono" id="telefono" value="{{ old('telefono', $vendedor->telefono) }}" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
                    @error('telefono')
                        <p class="text-red-500 text-sm mt-1">{{ $message }}</p>
                    @enderror
                </div>
                <div>
                    <a href="{{ route('vendedores.index') }}" class="bg-gray-500 text-white px-6 py-2 rounded-lg hover:bg-gray-600 focus:outline-none focus:ring focus:ring-gray-300 transition duration-200">Cancelar</a>
                    <button type="submit" class="bg-black text-white px-6 py-2 rounded-lg hover:bg-gray-800 focus:outline-none focus:ring focus:ring-gray-300 transition duration-200">Actualizar Vendedor</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

inventariadoDos/resources/views/vendedores/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container mx-auto px-4 py-8">
    <div class="flex justify-between items-center mb-6">
        <h2 class="text-2xl font-semibold text-gray-800">Lista de Vendedores</h2>
        <a href="{{ route('vendedores.create') }}" class="bg-blue-500 text-white px-6 py-2 rounded-lg hover:bg-blue-600 focus:outline-none focus:ring focus:ring-blue-300 transition duration-200">Crear Vendedor</a>
        <a href="{{ route('vendedores.pdf') }}" class="bg-green-500 text-white px-6 py-2 rounded-lg hover:bg-green-600 focus:outline-none focus:ring focus:ring-green-300 transition duration-200">Exportar PDF</a>

    </div>
    <div class="bg-white shadow-lg rounded-lg overflow-hidden">
        @if (session('success'))
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative mb-6" role="alert">
                {{ session('success') }}
            </div>
        @endif
        @if (session('error'))
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-6" role="alert">
                {{ session('error') }}
            </div>
        @endif
        <div class="overflow-x-auto">
            <table class="min-w-full bg-white border border-gray-300">
                <thead>
                    <tr class="bg-gray-100 text-gray-700">
                        <th class="px-6 py-3 border">ID</th>
                        <th class="px-6 py-3 border">Nombre</th>
                        <th class="px-6 py-3 border">Correo</th>
                        <th class="px-6 py-3 border">Teléfono</th>
                        <th class="px-6 py-3 border text-center">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($vendedores as $vendedor)
                    <tr class="bg-white">
                        <td class="px-6 py-4 border text-center">{{ $vendedor->id }}</td>
                        <td class="px-6 py-4 border">{{ $vendedor->nombre }}</td>
                        <td class="px-6 py-4 border">{{ $vendedor->correo }}</td>
                        <td class="px-6 py-4 border">{{ $vendedor->telefono }}</td>
                        <td class="px-6 py-4 border text-center">
                            <a href="{{ route('vendedores.show', $vendedor->id) }}" class="bg-blue-500 text-white px-4 py-2 rounded-full text-sm mr-2 hover:bg-green-600 focus:outline-none focus:ring focus:ring-green-300 transition duration-200">Ver</a>
                            <a href="{{ route('vendedores.edit', $vendedor->id) }}" class="bg-yellow-500 text-white px-4 py-2 rounded-full text-sm mr-2 hover:bg-yellow-600 focus:outline-none focus:ring focus:ring-yellow-300 transition duration-200">Editar</a>
                            @if($vendedor->tieneVentas())
                                <button type="button" class="bg-gray-500 text-white px-4 py-2 rounded-full text-sm hover:bg-gray-600 focus:outline-none focus:ring focus:ring-gray-300 transition duration-200" disabled>No se puede eliminar</button>
                            @else
                                <form action="{{ route('vendedores.destroy', $vendedor->id) }}" method="POST" class="inline-block">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded-full text-sm hover:bg-red-600 focus:outline-none focus:ring focus:ring-red-300 transition duration-200" onclick="return confirm('¿Estás seguro de eliminar este vendedor?')">Eliminar</button>
                                </form>
                            @endif
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection 

inventariadoDos/resources/views/vendedores/show.blade.php
<!-- resources/views/vendedores/show.blade.php -->

@extends('layouts.app')

@section('content')
<div class="container mx-auto px-4 py-8">
    <div class="bg-white shadow-lg rounded-lg overflow-hidden">
        <div class="px-6 py-4">
            <h1 class="text-2xl font-semibold mb-4">Detalle de Vendedor</h1>
            <div class="mb-4">
                <strong>Nombre:</strong> {{ $vendedor->nombre }}
            </div>
            <div class="mb-4">
                <strong>Correo:</strong> {{ $vendedor->correo }}
            </div>
            <div class="mb-4">
                <strong>Teléfono:</strong> {{ $vendedor->telefono }}
            </div>
            <div>
                <a href="{{ route('vendedores.index') }}" class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600">Volver</a>
            </div>
        </div>
    </div>
</div>
@endsection